apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service
  labels:
    app: leaderboard
    tier: service
    environment: dev
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000 
  selector:
    app: leaderboard
    tier: service
    environment: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-service
spec:
  selector:
    matchLabels:
      app:  leaderboard
      tier: service
      environment: dev
  replicas: 2
  template:
    metadata:
      labels:
        app: leaderboard
        tier: service
        environment: dev
    spec:
      containers:
      - name:  leaderboard
        image: index.docker.io/rmorais01/leaderboard:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 3000
---
