apiVersion: v1
kind: Service
metadata:
  labels:
    name: leaderboard-redis
    tier: backend
  name:  leaderboard-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
      name: leaderboard-redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-sentinel
    role: redis-sentinel
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
      name: leaderboard-redis 
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
      name: leaderboard-redis
    name: leaderboard-redis
spec:
  selector:
    matchLabels:
      name: leaderboard-redis
  replicas: 3 
  template:
    metadata:
      labels:
        name: leaderboard-redis
    spec:
      containers:
        - name: leaderboard-redis
          image: index.docker.io/rmorais01/samples:redis 
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
        - name: sentinel
          image: index.docker.io/rmorais01/samples:redis 
          env:
           - name: SENTINEL
             value: "true"
          ports:
           - containerPort: 26379 
      volumes:
      - name: data
        emptyDir: {}
---
